[workspace]
resolver = "2"
members = [
    "challenges/*/[0-9]/rs",
    "challenges/*/[0-9][0-9]/rs",
    "template/rs"
]

[workspace.dependencies]
ctor = "0.2.9"
anyhow = "1.0"
big-o-test = "0.2.8"
colored = "2.1"
log = "0.4"
simple_logger = "5.0.0"

